title: Optimize for happiness
description: Let's make life easier with simple scripting. Leave more space for joy. Grateful for everyone's encouragement and support!
theme: just-the-docs

url: https://joli-ta.github.io

aux_links:
  Template Repository: https://joli-ta.github.io

# remote_theme: just-the-docs/just-the-docs # if Settings - Pages - publishing from this branch.
