title: Optimize for happiness
description: Let's make life easier with simple scripting. Leave more space for joy. Grateful for everyone's encouragement and support!
remote_theme: just-the-docs/just-the-docs

url: https://joli-ta.github.io

favicon_ico: "/assets/images/fav1.png"
# logo: "/assets/images/fav1.png" # displayed instead of title

aux_links:
  GitHub Repository: https://github.com/Joli-ta/joli-ta.github.io

# Google Analytics Tracking (optional)
# Supports a CSV of tracking ID strings (eg. "UA-1234567-89,G-1AB234CDE5")
ga_tracking: G-VD8N8M65XP
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

date_format: "%Y.%m.%d"
# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%Y.%m.%d" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

enable_copy_code_button: false # For copy button on code

# More › http://kramdown.gettalong.org/quickref.html
# Options › http://kramdown.gettalong.org/options.html
kramdown:
  input:          GFM
  # https://github.com/jekyll/jekyll/pull/4090
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    default_lang: 'plaintext' # swift, plaintext does nothing https://github.com/rouge-ruby/rouge/wiki/List-of-supported-languages-and-lexers
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      # change to true to show line numbers
      line_numbers: false
      start_line: 1

search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

# remote_theme: just-the-docs/just-the-docs # (owner/theme) if Settings - Pages - publishing from this branch.
# theme: just-the-docs # if Settings - Pages - published with github actions
