title: Optimize for happiness
description: Let's make life easier with simple scripting. Leave more space for joy. Grateful for everyone's encouragement and support!
remote_theme: just-the-docs/just-the-docs

url: https://joli-ta.github.io

favicon_ico: "/assets/images/fav1.png"
logo: "/assets/images/fav1.png" # displayed instead of title

aux_links:
  GitHub Repository: https://github.com/Joli-ta/joli-ta.github.io

# remote_theme: just-the-docs/just-the-docs # (owner/theme) if Settings - Pages - publishing from this branch.
# theme: just-the-docs # if Settings - Pages - published with github actions
